services:
  - type: web
    name: pmb-app
    root_dir: tugasakhir
    buildCommand: mvn clean install
    startCommand: mvn spring-boot:run
    plan: starter
    envVars:
      - key: PORT
        value: 8080
